"""add users-groups relations

Revision ID: 026e4f4f732b
Revises: e2124e73845d
Create Date: 2025-08-06 14:11:43.349945

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "026e4f4f732b"
down_revision: Union[str, Sequence[str], None] = "e2124e73845d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_groups",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.Enum("ADMIN", "MEMBER", name="grouprole"), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "group_id"),
    )
    op.create_unique_constraint(None, "groups", ["name"])
    op.add_column("tasks", sa.Column("deadline", sa.DateTime(), nullable=True))
    op.alter_column("tasks", "title", existing_type=sa.VARCHAR(), nullable=False)
    op.add_column("users", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("hashed_password", sa.String(), nullable=False))
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.alter_column("users", "username", existing_type=sa.VARCHAR(), nullable=False)
    op.create_unique_constraint(None, "users", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column("users", "username", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("users", "is_active")
    op.drop_column("users", "hashed_password")
    op.drop_column("users", "updated_at")
    op.alter_column("tasks", "title", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("tasks", "deadline")
    op.drop_constraint(None, "groups", type_="unique")
    op.drop_table("user_groups")
    # ### end Alembic commands ###
