"""add username to emailverification

Revision ID: a24495bfa00a
Revises: 4416591e3bbc
Create Date: 2025-09-13 21:25:27.071269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a24495bfa00a'
down_revision: Union[str, Sequence[str], None] = '4416591e3bbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verifications', sa.Column('username', sa.String(), nullable=False))
    op.drop_index(op.f('ix_email_verifications_email'), table_name='email_verifications')
    op.create_index(op.f('ix_email_verifications_email'), 'email_verifications', ['email'], unique=True)
    op.create_unique_constraint(None, 'email_verifications', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email_verifications', type_='unique')
    op.drop_index(op.f('ix_email_verifications_email'), table_name='email_verifications')
    op.create_index(op.f('ix_email_verifications_email'), 'email_verifications', ['email'], unique=False)
    op.drop_column('email_verifications', 'username')
    # ### end Alembic commands ###
